version: '2'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    build: ./backend
    expose:
    - 8090
    ports:
      - "8090:8090"