service:
  name: "news-feed"

frameworkVersion: ">=1.28.0 <2.0.0"

custom:
  serverless-offline:
    port: 8090

package:
  exclude:
    - node_modules/**/aws-sdk/**
    - node_modules/**/serverless-offline/**
    - node_modules/**/serverless-plugin-include-dependencies/**
  individually: true
  excludeDevDependencies: false

provider:
  name: aws
  memorySize: 512
  runtime: nodejs10.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "iot:*"
      Resource: "*"
  timeout: 50
  versionFunctions: false

functions:
  authorizer:
    handler: utils/auth.authorize
  login:
    handler: controllers/login.login
    events:
      - http:
          path: api/v1/login
          method: post
          cors: true
  register:
    handler: controllers/register.register
    events:
      - http:
          path: api/v1/register
          method: post
          cors: true
  verifyUser:
    handler: controllers/verifyUser.verifyUser
    events:
      - http:
          path: api/v1/verifyUser
          method: post
          cors: true
  getNewsFeed:
    handler: controllers/getNewsFeed.getNewsFeed
    events:
      - http:
          path: api/v1/feeds
          method: get
          cors: true
          authorizer: authorizer
          

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-include-dependencies